name: Pin Check

on:
  push:
    branches: [main]
    paths: ['.github/workflows/**']
  pull_request:
    paths: ['.github/workflows/**']

permissions:
  contents: read

jobs:
  pin-check:
    uses: szl-holdings/.github/.github/workflows/pin-check-reusable.yml@1bbd857634a87d3a824be86ec7a79aaa8e4937e8
